
baseURL = "https://waynecater.com"
languageCode = "en-us"
title = "Wayne Cater"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Wayne Cater"
    description = "a simple guy with some creative passions"
    #description = "Artist, Author, Creative, Software Developer, Songwriter"
    githubUsername = "#"
    accent = "black"
    showBorder = false
    backgroundColor = "white"
    font = "Open Sans"  #"Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = []

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2



[[menu.main]]
    url = "/recordings/"
    name = "Music"
    weight = 3

[[menu.main]]
    url = "/books/"
    name = "Books"
    weight = 4

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:wayne@waynecater.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/wayne.cater"
    name = "fab fa-facebook"
    weight = 2

[[menu.icon]]
    url = "https://www.instagram.com/bwcater/"
    name = "fab fa-instagram"
    weight = 3

[[menu.icon]]
    url = "https://www.youtube.com/user/bwcater"
    name = "fab fa-youtube"
    weight = 4

[[menu.icon]]
    url = "https://soundcloud.com/waynecater"
    name = "fab fa-soundcloud"
    weight = 5

[[menu.icon]]
    url = "https://open.spotify.com/artist/15Qa1FHy9KZjXyUqhOonxl"
    name = "fab fa-spotify"
    weight = 5